name: Run unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'npm ci'
      - run: 'ng test --browsers=ChromeHeadless --watch=false --code-coverage'
