name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest    
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup node.js
    - run: 'npm ci'
    - run: 'npm run test:prod'
  
